[package]
name = "did_resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
did_parser = { path = "../did_parser" }
did_doc_builder = { path = "../did_doc_builder" }
lru = "0.10.0"
