[package]
name = "aries-vcx-cli"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
actix-web = "4.2.1"
anyhow = "1.0.66"
aries-vcx-agent = { path = "../aries-vcx-agent" }
clap = "4.0.29"
config = "0.13.3"
inquire = "0.5.2"
